/**
 * Indexora — LLM.txt Generator
 * Generates spec-compliant llms.txt in Markdown format per llmstxt.org
 */

interface LlmItemInput {
  type: string;
  title: string;
  handle?: string | null;
  description?: string | null;
  price?: string | null;
  stockStatus?: string | null;
  readinessScore: number;
}

interface GeneratorOptions {
  storeName: string;
  storeDomain: string;
  items: LlmItemInput[];
  format?: "markdown" | "yaml";
}

function truncate(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  return text.substring(0, maxLen).trim() + "...";
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

function getReadinessLabel(score: number): string {
  if (score >= 85) return "High";
  if (score >= 70) return "Medium";
  return "Low";
}

export function generateLlmsTxt(options: GeneratorOptions): string {
  const { storeName, storeDomain, items, format = "markdown" } = options;
  const products = items.filter((i) => i.type === "product");
  const collections = items.filter((i) => i.type === "collection");
  const pages = items.filter((i) => i.type === "page");
  const avgScore = items.length > 0
    ? Math.round(items.reduce((s, i) => s + i.readinessScore, 0) / items.length)
    : 0;

  if (format === "yaml") {
    return buildYaml(storeName, storeDomain, products, collections, pages);
  }
  return buildMarkdown(storeName, storeDomain, products, collections, pages, avgScore);
}

function buildMarkdown(
  name: string, domain: string,
  products: LlmItemInput[], collections: LlmItemInput[],
  pages: LlmItemInput[], avgScore: number,
): string {
  const l: string[] = [
    `# ${name}`, "",
    `> ${name} is an e-commerce store offering ${products.length} products across ${collections.length} collections.`,
    "> Generated by Indexora — ChatGPT and Gemini SEO Rank Booster.", "",
    `Last Updated: ${new Date().toISOString().split("T")[0]}`,
    `AI Readiness Score: ${avgScore}/100`,
    "Powered by: Indexora", "",
  ];

  if (products.length) {
    l.push("## Products");
    products.forEach((p) => {
      const desc = p.description ? truncate(stripHtml(p.description), 120) : "";
      const price = p.price ? ` $${p.price}.` : "";
      l.push(`- [${p.title}](https://${domain}/products/${p.handle}): ${desc}${price} AI Readiness: ${getReadinessLabel(p.readinessScore)}`);
    });
    l.push("");
  }

  if (collections.length) {
    l.push("## Collections");
    collections.forEach((c) => {
      const desc = c.description ? truncate(stripHtml(c.description), 120) : "";
      l.push(`- [${c.title}](https://${domain}/collections/${c.handle}): ${desc}`);
    });
    l.push("");
  }

  if (pages.length) {
    l.push("## Pages");
    pages.forEach((pg) => {
      const desc = pg.description ? truncate(stripHtml(pg.description), 120) : "";
      l.push(`- [${pg.title}](https://${domain}/pages/${pg.handle}): ${desc}`);
    });
    l.push("");
  }

  return l.join("\n");
}

function buildYaml(
  name: string, domain: string,
  products: LlmItemInput[], collections: LlmItemInput[],
  pages: LlmItemInput[],
): string {
  const l: string[] = [
    "store:", `  name: "${name}"`, `  domain: "${domain}"`,
    `  generated_by: "Indexora"`,
    `  last_updated: "${new Date().toISOString().split("T")[0]}"`, "",
  ];

  if (products.length) {
    l.push("products:");
    products.forEach((p) => {
      l.push(`  - title: "${p.title}"`);
      l.push(`    url: "https://${domain}/products/${p.handle}"`);
      if (p.price) l.push(`    price: "${p.price}"`);
      l.push(`    readiness: ${p.readinessScore}`);
    });
    l.push("");
  }

  if (collections.length) {
    l.push("collections:");
    collections.forEach((c) => {
      l.push(`  - title: "${c.title}"`);
      l.push(`    url: "https://${domain}/collections/${c.handle}"`);
    });
    l.push("");
  }

  if (pages.length) {
    l.push("pages:");
    pages.forEach((pg) => {
      l.push(`  - title: "${pg.title}"`);
      l.push(`    url: "https://${domain}/pages/${pg.handle}"`);
    });
  }

  return l.join("\n");
}
