# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51a28e5095d4c505753255c19332bc3f"
name = "Indexora Chatgpt AI SEO"
application_url = "https://shopify-indexora-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ 
  "https://shopify-indexora-production.up.railway.app/auth/callback",
  "https://shopify-indexora-production.up.railway.app/auth/shopify/callback",
  "https://shopify-indexora-production.up.railway.app/api/auth/callback"
]

[app_proxy]
prefix = "apps"
subpath = "indexora-chatgpt-seo"
url = "https://shopify-indexora-production.up.railway.app/app-proxy"
